import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";



const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],

});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning
      className={`${nunito.className} h-full antialiased`} data-theme='light'
    >
      <body className="min-h-full flex flex-col bg-[#fcf8ff]">
         <Navbar/>
         <main className="container mx-auto ">
             {children}
         </main>


        </body>
    </html>
  );
}
